// apps/02/react-clock/src/app/clock/clock-container.tsx
export type ClockContainerProps = {
  children: React.ReactNode[];
};
export function ClockContainer({ children }: ClockContainerProps){
  return (
    <div className="clock">
      <div className="outer-clock-face">
        <div className="marking marking-one"></div>
        <div className="marking marking-two"></div>
        <div className="marking marking-three"></div>
        <div className="marking marking-four"></div>
        <div className="inner-clock-face">
          {children}
        </div>
      </div>
    </div>
  );
}

// apps/02/angular-clock/src/app/clock/clock-container.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-clock-container',
  template: `
    <div class="clock">
      <div class="outer-clock-face">
        <div class="marking marking-one"></div>
        <div class="marking marking-two"></div>
        <div class="marking marking-three"></div>
        <div class="marking marking-four"></div>
        <div class="inner-clock-face">
          <ng-content></ng-content>
        </div>
      </div>
    </div>
  `,
})
export class ClockContainerComponent {}
