// apps/02/react-clock/src/app/app.tsx
import { useEffect, useState } from 'react';
import { ClockContainer } from './clock/clock-container';
import { ClockDigital } from './clock/clock-digital';
import { ClockHand } from './clock/clock-hand';

export function App() {
  const [date, setDate] = useState(new Date());

  useEffect(() => {
    const i = setInterval(() => {
      setDate(new Date());
    }, 1000);

    return () => clearInterval(i);
  }, []);

  return (
    <ClockContainer>
      <ClockDigital date={date} />
      <ClockHand type="HOUR" time={date.getHours()} />
      <ClockHand type="MINUTES" time={date.getMinutes()} />
      <ClockHand type="SECONDS" time={date.getSeconds()} />
    </ClockContainer>
  );
}

export default App;

// apps/02/angular-clock/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { interval, map, startWith } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  time$ = interval(1000).pipe(
    map(() => new Date()),
    startWith(new Date())
  );
}

<app-clock-container *ngIf="time$ | async as time">
  <app-clock-digital [date]="time"></app-clock-digital>
  <app-clock-hand type="HOUR" [time]="time.getHours()"></app-clock-hand>
  <app-clock-hand type="MINUTES" [time]="time.getMinutes()"></app-clock-hand>
  <app-clock-hand type="SECONDS" [time]="time.getSeconds()"></app-clock-hand>
</app-clock-container>
